username: "{{ lookup('env', 'USER') }}"
home: "{{ lookup('env', 'HOME') }}"
config: "{{ home }}/.config"
build: "{{ home }}/.build"

default_roles:
  - system
  - bash
  - git
  - packages
  - font
  - go
  - nodejs
  - nvim
  - rust
  - hyprland
  - hyprdot
  - ghostty
  - fuzzel
  - flatpak
  - app
  - ssh
  - virtualization
  # - blender
  - nnn
  - typst

install_path: "/usr/src"
bin_path: "/usr/local/bin"
awww:
  repos: "https://codeberg.org/LGFae/awww.git"
  version: "main"

op:
  ssh:
    github:
      notfoundy:
        - name: github_key
          vault_path: "op://Private/github_key"
        - name: n8n_key
          vault_path: "op://Private/n8n_key"
